<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="scaffolds" nsURI="scaffolds" nsPrefix="scaffolds">
  <eClassifiers xsi:type="ecore:EClass" name="ScaffoldGraph">
    <eStructuralFeatures xsi:type="ecore:EReference" name="contigs" upperBound="-1"
        eType="#//Contig" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Contig">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" lowerBound="2"
        upperBound="2" eType="#//Vertex" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="multiplicity" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Edge">
    <eStructuralFeatures xsi:type="ecore:EReference" name="vertices" lowerBound="2"
        upperBound="2" eType="#//Vertex" eOpposite="#//Vertex/edges"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="weight" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="distance" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Vertex">
    <eStructuralFeatures xsi:type="ecore:EReference" name="edges" upperBound="-1"
        eType="#//Edge" eOpposite="#//Edge/vertices"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="num" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
</ecore:EPackage>
