<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="FeatureModel" nsURI="FeatureModel" nsPrefix="FeatureModel">
  <eClassifiers xsi:type="ecore:EClass" name="FeatureModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="RootFeature" lowerBound="1"
        eType="#//RootFeature" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="FConst" upperBound="-1"
        eType="#//FeatureConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RootFeature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConfConst" lowerBound="1"
        upperBound="-1" eType="#//ConfigConstraint" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="FeatureConstraint" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Features" lowerBound="2"
        upperBound="2" eType="#//Feature"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//Type"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Feature">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Config" lowerBound="1"
        eType="#//ConfigConstraint" eOpposite="#//ConfigConstraint/ConfFeatures"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="kind">
    <eLiterals name="optional"/>
    <eLiterals name="mandatory" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConfigConstraint" abstract="true" eSuperTypes="#//Constraint">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="kind" eType="#//kind"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ConfFeatures" upperBound="-1"
        eType="#//Feature" containment="true" eOpposite="#//Feature/Config"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="And" eSuperTypes="#//ConfigConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Or" eSuperTypes="#//ConfigConstraint"/>
  <eClassifiers xsi:type="ecore:EClass" name="Xor" eSuperTypes="#//ConfigConstraint"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Type">
    <eLiterals name="require"/>
    <eLiterals name="exclude" value="1"/>
  </eClassifiers>
</ecore:EPackage>
